- CHANGELOG.md
- setup.py
- smbprotocol/connection.py
- smbprotocol/open.py
- smbprotocol/transport.py
- smbprotocol/tree.py
Trying to connect to a host that was routable but the SMB port was blocked would hang the process. This PR makes sure the initial socket connection honours the connection timeout set.
It also fixes up some deprecated escape sequences that Python 3.8 was warning about.
> Add timeout to initial socket connection, fix deprecated escape sequences

- CHANGELOG.md
- README.md
- appveyor.yml
- setup.py
- smbprotocol/session.py
- tests/test_session.py
Adds supports for authentication with SSPI on Windows which adds the following when running on Windows;
* Implicit credentials, uses the current user's credentials, and
* Kerberos authentication
Also uses a newer class from `ntlm-auth` for better simplicity and maintained.
Implements https://github.com/jborean93/smbprotocol/issues/7
> Add Windows SSPI support and use newer NTLM class

- CHANGELOG.md
- setup.py
- smbprotocol/create_contexts.py
- smbprotocol/open.py
- smbprotocol/transport.py
- tests/test_create_contexts.py
- tests/test_open.py
- tests/test_transport.py
Fixes up the socket connection to support IPv6 addresses. Also fixes up the create response parsing when receiving a lease response.
Fixes https://github.com/jborean93/smbprotocol/issues/11
Fixes https://github.com/jborean93/pypsexec/issues/17
> Support IPv6 and fix Lease response messages

- .travis.yml
- CHANGELOG.md
- setup.py
- tox.ini
Drop Python 2.6 support and added Python 3.8 officially to the Travis CI list.
> Drop support for Python 2.6, added 3.8 to CI officially

- .gitignore
- CHANGELOG.md
- appveyor.yml
- setup.py
- smbprotocol/_text.py
- smbprotocol/change_notify.py
- smbprotocol/connection.py
- smbprotocol/structure.py
- smbprotocol/transport.py
- tests/test_change_notify.py
- tests/test_connection.py
- tests/test_open.py
- tests/test_session.py
- tests/test_structure.py
- tests/test_text.py
- tests/test_transport.py
- tests/test_tree.py
Changed the listener and message processing side of smbprotocol to run in a thread in the background. This is designed to simplify the message processing and to better handle asynchronous messages sent to and from the server.
Also adds a `FileSystemWatcher` that can be used to detect when a change has occurred in a directory on a remote server. Also introduced a way to cancel background running requests.
> New Listener and FileSystemWatcher

- smbclient/__init__.py
- smbclient/_os.py
- smbclient/shutil.py
- tests/test_smbclient_os.py
- tests/test_smbclient_shutil.py
Added various methods like copy2, copytree etc. Also added a kwarg that allows to perform copying server side. Many methods are copied and adapted from their python2 shutil counterpart to mimic their behavior. Further, a set of integration tests that at least cover the happy paths was added. @jborean93 let me know what you think.
> Add various shutil methods

- CHANGELOG.md
- smbclient/_io.py
- tests/test_smbclient_os.py
During a read we were incorrectly incrementally increasing the offset with the size of the data collection so far instead of what was read in the SMB Read operation. This PR fixes up the logic to increase the offset only by the amount of data read by each SMB call.
This was an issue before when reading files that were between 131073 and 196609 bytes (other ranges were most likely affected as well). With the previous logic, the 3rd SMB call would have an offset that is larger than the file itself resulting in an `STATUS_END_OF_FILE` exception. Now the offset should be calculated properly.
Fixes https://github.com/jborean93/smbprotocol/issues/20
> smbclient - fix reads on large files

- CHANGELOG.md
- setup.py
- smbprotocol/change_notify.py
- smbprotocol/connection.py
- smbprotocol/open.py
- smbprotocol/session.py
- smbprotocol/tree.py
A common logging pattern is for smbprotocol to output the SMB2 messages sent across the write on the DEBUG level logging. This can cause a slowdown for large messages like an SMB2 Read Response or SMB2 Write Request with a large amount of data.
Instead of calling `__str__` in the `log.debug()` call we instead pass the object which has the benefit of only calling `__str__` if debug level logging is enabled. Because of this the performance hit of logging these large messages only happens if DEBUG level logs are enabled.
I can't seem to find the original reporter for this issue but thanks for bringing this to my attention if you are following this.
> Speed up logging statements when logging isn't used

- CHANGELOG.md
- README.md
- smbclient/_io.py
- smbclient/_os.py
- smbprotocol/change_notify.py
- smbprotocol/exceptions.py
- smbprotocol/open.py
- smbprotocol/session.py
- tests/test_change_notify.py
- tests/test_exceptions.py
- tests/test_open.py
- tests/test_tree.py
- tox.ini
To make it easier to catch only a specific status this creates an exception type for each known status code.
> Create separate exception types for each status code

- CHANGELOG.md
- smbprotocol/connection.py
When testing a long running connection to a Windows Server it seems like if there was no activity on the session, Windows will close it. If there are no active sessions on a connection then Windows will close the connection including the socket opened by the client. This causes a broken pipe error to be raised on the first operation of any sessions on that connection if no activity has occurred.
What this PR does is to send an SMB Echo request for every session of that connection 10 minutes after no activity has occurred. Windows will close the connection at around ~16 minutes and when testing this same code with Samba I found the connection isn't closed before the request is sent.
Fixes https://github.com/jborean93/smbprotocol/issues/31
> Fix long running pipe socket broken error

- smbclient/_pool.py
The naming of the connection_key isn't consitent between register_session and delete_session
> Consistent connection_key naming

- tests/test_smbclient_os.py
smbclient._os.CHUNK_SIZE appears to be completely nonfunctional. It is never read anywhere in the codebase. I'm guessing smbclient._os.CHUNK_SIZE is a leftover from a previous implementation that used it.
> Remove smbclient._os.CHUNK_SIZE.

- CHANGELOG.md
- smbclient/_io.py
- smbprotocol/connection.py
- tests/test_smbclient_os.py
Fixes up the logic that calculates how many credits were granted by the
server. Previously we considered each message in a compound request as 1
credit even though the credit amount was 0 in the header. Instead we
need to not count those as the last header has the proper credit amount.
Also fixes an issue with the read offset being doubled when calling
`read()`. This was a recent change and not part of any release.
> Fix up credit calculation and read offsets

- tests/conftest.py
Each test should start with their own session to ensure another can't pollute the environment.
> Ensure tests start with fresh connection

- smbclient/_pool.py
- smbprotocol/connection.py
- smbprotocol/session.py
I have added in a way to pass extra kwargs to `spnego.client`. The primary motivation behind doing this was to be able to disable NTLM fallback authentication while using the high-level API, but I think the low-level API doesn't have support for this either, so this PR will add this functionality in both places.
I have marked this as a WIP for now as I haven't written any tests, but I wanted to get it on your radar.
> Allow passing kwargs to spnego.client from high-level API

- tests/test_smbclient_shutil.py
It seems like different versions of Samba/Windows can return a list enumeration a bit differently. Make this test less reliant on the strict order to ensure it passes in CI.
> Make test less strict on dir ordering

- CHANGELOG.md
- smbprotocol/session.py
- tests/test_session.py
The GSS Negotiation Token from the negotiation response is a [NegTokenInit2](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-spng/8e71cf53-e867-4b79-b5b5-38c92be3d472) token that contains a list of mechs the server supports and is parsed by the Negotiate process when selecting the optimistic protocol. When someone explicitly requests `ntlm` or `kerberos` auth we were still passing in this token but neither pure Kerberos or NTLM is able to parse the SPNEGO token structure causing a failure when generating the first token.
This PR blanks out that token when not using `negotiate` auth and fixes a logic bug that becomes present when using pure NTLM authentication not wrapped in SPNEGO.
Fixes https://github.com/jborean93/smbprotocol/issues/74
> Fix up auth logic for non-negotiate auth

- CHANGELOG.md
- azure-pipelines.yml
- setup.py
- smbclient/_pool.py
- smbprotocol/_compat.py
- smbprotocol/connection.py
- smbprotocol/exceptions.py
- smbprotocol/transport.py
- tests/test_connection.py
- tests/test_smbclient_os.py
- tests/test_transport.py
The current mechanism used to read responses from the TCP socket is quite complex but summarised in a very simplified matters involves 2 different threads
* TCP thread
* Constantly calls `socket.recv()` to read SMB responses and adds them to an internal queue once received
* Connection thread
* Reads from the internal queue for any messages from the TCP thread
* Unpacks each message and fires the request event saying it has been received
This whole mechanism does work but it's very brittle to any failures in any of those steps. If the socket is closed for whatever reason the connection thread will be notified and stop listening for more messages. The issue here is that the main thread waiting for the response is never notified of this failure causing it to hang indefinitely. There are …
> Fix TCP Receiver Hangs

- smbclient/shutil.py
Ultimately I want to extend `copytree` to allow copying to local, but as a first step towards that, this moves out the check for a remote path to a named function.
> Use a named function when checking whether a path is remote.

- CHANGELOG.md
- setup.py
- smbclient/_io.py
- smbclient/_os.py
- smbprotocol/exceptions.py
- tests/conftest.py
- tests/test_smbclient_os.py
It turns out anything being opened as a SMBFileTransaction does not handle the path being part of a DFS path. This PR moves the DFS resolver to the transaction commit code and also adjusts the logic for `rename` and `replace` to validate the volume based on the resolved path and not just what the input strings are.
Fixes https://github.com/jborean93/smbprotocol/issues/85
> Fix up replace/rename when running on a DFS path

- CHANGELOG.md
- smbclient/_os.py
- smbclient/shutil.py
- tests/test_smbclient_os.py
The values of `scandir` can then go on to call `stat` which currently fails if `scandir` was originally called with a custom cache. This fixes up that logic so subsequent calls continue to use that cache.
This also fixes up `rmtree` where it didn't continue to use the cache when removing directory children.
Fixes https://github.com/jborean93/smbprotocol/issues/87
> Fix up connection cache for scandir and rmtree

- CHANGELOG.md
- azure-pipelines.yml
- setup.py
- tests/constraints.txt
- tox.ini
It's time to move on, this is getting harder to run in CI and people on these versions can still continue to use older releases fi they wish.
Fixes https://github.com/jborean93/smbprotocol/issues/94
> Bump version and drop python 2.7/3.5

- smbprotocol/transport.py
Address the (presumably) Linux-specific race condition in socket.shutdown()
See https://github.com/FreeOpcUa/python-opcua/issues/739 for a similar issue/fix
> Ignore ENOTCONN socket errors

- smbclient/__init__.py
Objects of this type are returned by the `scandir` generator.
> Add `SMBDirEntry` to exposed symbols

- CHANGELOG.md
- smbprotocol/structure.py
- tests/test_structure.py
Python has a max `datetime` value of `9999-12-31T23:59:59.999999Z` while FILETIME can go beyond this. We handle the overflow error by setting the datetime field to that max value. This unfortunately means that data can be lost but this is so far into the future I don't really think it's too much of a problem. The alternative is to not use `datetime.datetime` which has far reaching compatibility issues that it isn't worth looking into.
Fixes https://github.com/jborean93/smbprotocol/issues/114
> Datetime overflow

- azure-pipelines.yml
- tests/test_smbclient_shutil.py
Fixes #119
This adds macOS tests runs.
I have only enabled macOS as these jobs are slow ...and I think that 3.9 should be the most popular version.
If errors are found on macOS with other Python version, we can later extend the matrix.
The is some yaml duplication, but I didn't want to add template as I think that the duplication can be managed.
The Samba docker tests are skipped on macOS.
It looks like the test failing on macOS were just some test to check that os.chmod is used and are not tests for smbprotocol.
I have skipped them.
--------------
I don't know how to install docker on macOS from CLI.
I guess that instead of docker, we can also have samba installed via homebrew and configured in Azure and executed in the background 
Or try to run some tests via macOS native SMB server …
> Run tests on macOS with Python 3.9.

- CHANGELOG.md
- smbclient/_io.py
- smbprotocol/connection.py
Turns out the logic I had for calculating the credit charge was incorrect. The existing logic failed when attempting a read of `262145` bytes as the code was thinking it cost 4 credits instead of 5. This PR adjusts the credit calculation for this scenario.
Fixes https://github.com/jborean93/smbprotocol/issues/112
> Fix up credit charge calculation

- CHANGELOG.md
- smbprotocol/connection.py
- smbprotocol/session.py
We never removed the requests from the outstanding request table if the status wasn't a success or pending. This results in the requests building up over time for operations that expect a failure message like `smbclient.listdir()`. Instead we always clear the request from the outstanding table unless
* it's a pending response and we are waiting - the final response will delete it
* it's a stopped on symlink - the redirected request response will delete it
Fixes https://github.com/jborean93/smbprotocol/issues/127
> Remove outstanding requests on failures as well

- smbclient/_io.py
Just tried the new release and wondered about an unstructured output in my logs.
> Fix output (replace print())

- CHANGELOG.md
- setup.py
- smbclient/_pool.py
Setting the `domain_controller` will kick of an IPC tree connect which will try to get an instance of that config for the credentials to use. Since the config instance is not stored in the singleton dict it would now be a brand new config without any credentials causing a failure if Kerberos wasn't used. This method ensures that `domain_controller` is only ever set once all the other properties are when creating a new instance.
Fixes https://github.com/jborean93/smbprotocol/issues/109
> Fix up domain_controller ClientConfig authentication

- smbprotocol/connection.py
- smbprotocol/transport.py
- tests/test_connection.py
- tests/test_transport.py
This PR implements health checks for server connections to prevent infinite blocks. 
When the server connection gets lost and no data is received anymore, the receiving thread waits infinitely. After 10 minutes a `TimeoutError` is raised in `transport.recv()` and a keepalive message gets sent to the server.
However, there were no checks in place if the server actually answers the keepalive echo requests, which lead to an infinite timeout loop.
My implementation checks on timeouts, whether unanswered keepalive echo requests exist. These keepalives are only sent during (previous) timeouts. When such keepalives exist, that means the server did not respond within `2 * timeout`. Then we assume that the connection is dead and close it.
Relates https://github.com/jborean93/smbprotocol/issues/117
> Connection health checks

- smbclient/_os.py
`stat()` supports `follow_symlinks=False` passed in `kwargs`, but `SMBRawIO(path, **kwargs)` does not and raises an Exception.
> Support not following symlinks in SMBDirEntry.from_path

- smbclient/_io.py
Since `self.__kwargs` is set in `SMBRawIO.__init__`, its name will always be `_SMBRawIO__kwargs`.
This fixes connection_cache not being passed to get_smb_tree in dfs referrals
> Fix incorrect name mangling

- CHANGELOG.md
- setup.py
- smbclient/__init__.py
Adds `smbclient.path` to `smbclient` allowing easier imports and utilisation of that library.
Fixes https://github.com/jborean93/smbprotocol/issues/157
> Add path to smbclient import and bump version

- CHANGELOG.md
- src/smbclient/_io.py
- src/smbclient/_os.py
- src/smbprotocol/connection.py
Ensure that opening a file on a DFS marked share contains the
SMB2_FLAGS_DFS_OPERATIONS flag and create filename contains the DFS path
to parse and not just the tree relative path.
Related https://github.com/jborean93/smbprotocol/issues/170.
> Improve DFS file opens

- src/smbclient/_io.py
- src/smbclient/_os.py
- src/smbclient/_pool.py
- src/smbprotocol/connection.py
Turns out the path is resolved correctly and I can use the DFS path to be normalized but I need to ensure
* The DFS path is done as part of `get_smb_tree` so all callers get this new path
* The header is build to include the DFS operation flag for more than just a CREATE request
Fixes: https://github.com/jborean93/smbprotocol/issues/170#issuecomment-1221858156
> Fix rename operations for a DFS path

- CHANGELOG.md
- src/smbprotocol/connection.py
- tests/test_connection.py
When using a negotiate request with a hostname that is a multiple of 8 bytes the code will add 8 extra padding bytes. While this works on some servers others are stricter and can fail the request. This commit fixes up the padding to ensure no padding is used if the length of a context request aligns with the 8 byte boundary it is in.
Fixes: https://github.com/jborean93/smbprotocol/issues/199
> Fix negotiate request context padding

- CHANGELOG.md
- pyproject.toml
- src/smbclient/_pool.py
When attempting to resolve the DFS path on a BadNetworkName error it may error with a DFS related error message. This error should be ignored if the error was stating DFS is unavailable. The whole check can also be avoided entirely if the server does not indicate it supports DFS in the capabilities it sends back.
Fixes: https://github.com/jborean93/smbprotocol/issues/196
> Raise original BadNetworkName error on DFS failure

- src/smbclient/shutil.py
- tests/test_smbclient_shutil.py
Step 1 to address https://github.com/jborean93/smbprotocol/issues/221
Splitting this into two PRs.
I had trouble getting the tests to work locally (even the unit tests that don't need an actual samba share to talk to), but tested manually. I am expecting the test I added to pass in CI
> adding support for remote to local operations in shutil.py::copytree

- src/smbclient/_os.py
- src/smbclient/shutil.py
- tests/test_smbclient_shutil.py
pt. 2 of addressing https://github.com/jborean93/smbprotocol/issues/221
Tackling symlinks looks a little daunting, so I'd like to circle back after making sure my current approach is aligned with the project.
It crossed my mind to have both `LocalDirEntry` and `SMBDirEntry` inherit from the same abstract class, but I've opted to keep it simple
> adding support for local to remote operations in shutil.py::copytree

- src/smbclient/__init__.py
- src/smbprotocol/__init__.py
I found that your library modifies logger settings.
This should be done explicitly by user or application which uses the library, but never library itself.
> Do not setup logging in libraries

- CHANGELOG.md
- src/smbclient/_io.py
- tests/test_smbclient_os.py
The code that handles a missing path does not currently record existing DFS target servers that have been tried resulting in a recursion error. By ensuring a DFS target is only retried if it hasn't already it should avoid this recursion problem.
Fixes: https://github.com/jborean93/smbprotocol/issues/228
> Fix DFS recurision for missing files

- CHANGELOG.md
- pyproject.toml
- src/smbclient/__init__.py
- src/smbclient/_os.py
- tests/test_smbclient_os.py
Adds the property smb_info to the scandir enumerated result which contains the already retrieved metadata on the file during the scan operation. This provides a more efficient way for callers to retrieve information like the file times, sizes, attributes straight away without having to call .stat() which results in another SMB request to the server.
Fixes: https://github.com/jborean93/smbprotocol/issues/250
> Add smb_info to a scandir result

- CHANGELOG.md
- src/smbprotocol/structure.py
- tests/test_connection.py
- tests/test_create_contexts.py
- tests/test_file_info.py
- tests/test_open.py
- tests/test_structure.py
Stop using a deprecated function that was deprecated in Python 3.12 and ensure any datetime values unpacked from SMB messages are using the UTC timezone instead of being a naive tz.
> Use UTC tzinfo datetime values

- src/smbclient/_pool.py
- src/smbprotocol/connection.py
- src/smbprotocol/session.py
The library hang when following these steps:
- Connect using register_connection() to a SMB server.
- Shut down the server, using the normal shutdown procedure.
- Call any kind of disconnect(), like reset_connection_cache()
Now the library hangs.
This is because of the connection.receive() function is called against a dead server, without a timeout.
This pull request suggests setting the default timeout of the connection.receive() function to the same value as the default timeout of the other functions.
> Added default timeout on connection.receive()

- src/smbprotocol/transport.py
- tests/test_transport.py
Fixes #259
Apply the same format that was used in older version and update the existing automated test.
> Show low-level OS error on TCP connection errors.

- CHANGELOG.md
- README.md
- src/smbprotocol/connection.py
- tests/test_connection.py
Fixes #254 
This is mostly to help with autoamted tests.
On disconnect wait a bit for the thread.
If the thread is still running, disconect will still return, just like before.
I have created a fixte to reduce the duplicate code required to setup a connection and all the try/finally for cleanup.
As as drive-by I have updated the docstring for echo test and wrote another test for echo, as I was using those tests to learn about testing code.
As a drive by, I have updated the README with some info a found during initial dev.
Feel free to revert those changes.
> Wait for message thread to stop on disconnect.

- CHANGELOG.md
- src/smbprotocol/connection.py
Change to not set the SessionId and TreeId in the SMB headers of related compound requests as it is not in the spec. The spec only states the FileId used in the first create should be set to all bits and not these other two fields.
Fixes: https://github.com/jborean93/smbprotocol/issues/260
> Fix up compound request session and tree ids

- CHANGELOG.md
- src/smbclient/shutil.py
- tests/test_smbclient_shutil.py
Opens the source file used in shutil.copyfile with share_access="r" to ensure that it can be copied even if something else already has it opened with read access and grants further opens.
Fixes: https://github.com/jborean93/smbprotocol/issues/258
> Shutil.copyfile will open source with read share

- CHANGELOG.md
- src/smbprotocol/session.py
Fix up the endless loop that can occur during authentication when the authentication context was complete but the server still continued to respond with an access token. This should not happen with any major server but still possible with some more niche implementations like impacket.
Fixes: https://github.com/jborean93/smbprotocol/issues/261
> Fix up endless auth loop

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
- requirements-dev.txt
Bumps the version after the last release and update the dev dependencies to reflect the latest version available today. This commit also drops Python 3.7 as it has been EOL for a few months now and some dev dependencies no longer work on 3.7.
> Bump version and update dev deps

- src/smbclient/_pool.py
- src/smbprotocol/connection.py
This PR extends the configurability of the SMB Connection class and register_session methods to allow modifying the transport.recv timeout used for both keep-alive checks that keep Windows from closing a connection at ~16 minutes, and for checking the health of the connection.
In the usecase of my application, the SMB connection is used over an unstable network, which sometimes loses the connections between the machines. This triggers Connection timed out errors from the health check implemented in _process_message_thread, but only after 10+ minutes (the hardcoded timeout) where the application hangs. I would like to be able to configure this timeout to be smaller for use cases like this, to perform the health check more often, and be able to handle the timeout error in a reasonable …
> Customizable receive timeout for SMB Connection

- CHANGELOG.md
- pyproject.toml
- src/smbclient/_pool.py
- src/smbprotocol/connection.py
Fixes the session lookup logic when the logoff response contains a session id of 0. This occurs when using an Impacket server and will have the client just lookup the session id from the request.
Also adjusts the connection cache clearing behaviour to remove the connection from the cache regardless of the result of the disconnect behaviour.
Fixes: https://github.com/jborean93/smbprotocol/issues/289
> Fix Impacket logoff session id check

- src/smbclient/__init__.py
- src/smbclient/_os.py
- tests/test_smbclient_os.py
A simple change in theory, let me know if I messed up anything with layout / documentation etc.
I haven't got a huge array of machines to test against, but it works on my test device.
Closes #292
> Add `smbclient.liststreams` to enumerate ADS streams

- src/smbclient/_os.py
- src/smbclient/_pool.py
- src/smbprotocol/session.py
I won't lie, overloads are super verbose. But I worked off the ones for the stdlib `open()`, so it's "known good" at least.
I tested this by looking through all the test_smbclient_os opens and making sure the correct type was inferred.
I also added some extras so you can get typed connection details from an fd. It still kinda sucks (because something like the buffer sizes are None until `connect` is called) but at least it has intellisense.
Unfortunate API break: I couldn't work out a way to set the file/dir/pipe arg to specific values without forcing kwargs with * or moving the arg. I chose the latter, interested to hear your thoughts.
> Add some type annotations, most notably to `smbclient.open_file`

- src/smbprotocol/open.py
- tests/test_open.py
This PR adds support for locking and unlocking byte ranges in files.
> Implement SMB2 LOCK operation

- src/smbclient/_os.py
- tests/test_smbclient_os.py
The doc for utime:
> If times is not None, it must be a 2-tuple of the form (atime, mtime) where each member is an int or float expressing seconds.
However, providing floats throws:
```
TypeError: Cannot parse value for field last_access_time of type float to an int
```
This fixes that and adds a unit test to verify.
> Allow floating point times for smbclient.utime
